version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "honeycode-app"
s3_bucket = "aws-sam-cli-honeycode-test-20230606"
s3_prefix = "honeycode-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
